# Generated by Django 3.2.7 on 2021-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.IntegerField(max_length=8)),
                ('telefono', models.IntegerField(max_length=9)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
