# Generated by Django 3.2.7 on 2021-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(max_length=9, unique=True),
        ),
    ]
