# Generated by Django 3.2.7 on 2021-09-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 8, 57, 35, 116475), verbose_name='date published'),
        ),
    ]
