# Generated by Django 3.2.8 on 2021-10-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(default='descripcion', max_length=200),
        ),
    ]
