# Generated by Django 3.2.9 on 2021-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecDevolucion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='fecPrestamo',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
