# Generated by Django 3.2.9 on 2021-11-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211114_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='Usuario',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='usuario',
            field=models.CharField(default='jose', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='libro',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
